#!/usr/bin/bash

# Checks that all msgid strings in .po files are identical in the remove-old-kernels script.
# On error, the string in the offending .po file is printed out.
# Number of strings reported should be identical for all languages.

clear
for pofile in po/*pot po/*po; do
	echo "Checking - ${pofile}"
	entries=0
	while read line ; do
		
		findid="$(echo "$line" | grep 'msgid'|cut -d'"' -f2)"
		[[ ${#findid} = 0 ]] && continue
		# Skip these two strings as they include a variable in the script.
		if echo "$findid"|grep -q "that would be used"; then
			continue
		fi
		((entries++))
		if ! fgrep -q "$findid" remove-old-kernels; then
			echo "${pofile} - ${findid}"
		fi
	done < "${pofile}"
	echo strings - $entries
done
	

