#!/bin/bash
# Pass --desktop flag to indicate desktop launch
pkexec /usr/sbin/remove-old-kernels --desktop "$@"
exit_code=$?

if (( exit_code == 126 )) || (( exit_code == 127 )); then
    exit 0
fi

exit $exit_code
