#!/bin/bash
# Pass -d flag to indicate desktop launch
pkexec /usr/sbin/remove-old-kernels -d "$@"
exit_code=$?

if (( exit_code == 126 )) || (( exit_code == 127 )); then
    exit 0
fi

exit $exit_code
